'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eOrders
    
    '''<summary>
    '''ErrorNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OkNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OkMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtFechaHora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaHora As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDocDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDocDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtAlmacen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlmacen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDistribuidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDistribuidor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstTP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstDirs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstDirs As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LblDE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDE3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtDir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDir As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtItemCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtItemCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNombre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Disponible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disponible As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCantidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblPrecio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPrecio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMoneda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoneda As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtDescuento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDescuento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblImpuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblImpuesto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIVA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblSubTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSubTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtDisp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDisp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LstPromos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstPromos As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstMV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstMV As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstStock As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''RefeBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefeBanco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstMP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstFP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstUso As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstTipo As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblErrId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnGenerarPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerarPedido As Global.System.Web.UI.WebControls.Button
End Class
