'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eOrdersViewer
    
    '''<summary>
    '''TxteOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxteOrder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDocDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDocDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtAlmacen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlmacen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDistribuidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDistribuidor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstTP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstDirs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstDirs As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LblDE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDE3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtDir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDir As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstPromos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstPromos As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstMV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstMV As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstStock As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''RefeBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefeBanco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstMP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstFP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstUso As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LstTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstTipo As Global.System.Web.UI.WebControls.ListBox
End Class
