'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModCustomer
    
    '''<summary>
    '''TxtUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUser As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtAlmacen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlmacen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhsName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDistribuidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDistribuidor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSlpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSlpName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCardName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LstDirsE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstDirsE As Global.System.Web.UI.WebControls.ListBox
End Class
